gboolean purple_core_init (const char* ui);
void purple_core_quit (void);
gboolean purple_core_quit_cb (gpointer unused);
const char* purple_core_get_version (void);
const char* purple_core_get_ui (void);
PurpleCore* purple_get_core (void);
void purple_core_set_ui_ops (PurpleCoreUiOps* ops);
PurpleCoreUiOps* purple_core_get_ui_ops (void);
gboolean purple_core_migrate (void);
gboolean purple_core_ensure_single_instance (void);
GHashTable* purple_core_get_ui_info (void);
