PurpleLog* purple_log_new (PurpleLogType type, const char* name, PurpleAccount* account, PurpleConversation* conv, time_t time, const struct tm* tm);
void purple_log_free (PurpleLog* log);
void purple_log_write (PurpleLog* log, PurpleMessageFlags type, const char* from, time_t time, const char* message);
char* purple_log_read (PurpleLog* log, PurpleLogReadFlags* flags);
GList* purple_log_get_logs (PurpleLogType type, const char* name, PurpleAccount* account);
GHashTable* purple_log_get_log_sets (void);
GList* purple_log_get_system_logs (PurpleAccount* account);
int purple_log_get_size (PurpleLog* log);
int purple_log_get_total_size (PurpleLogType type, const char* name, PurpleAccount* account);
int purple_log_get_activity_score (PurpleLogType type, const char* name, PurpleAccount* account);
gboolean purple_log_is_deletable (PurpleLog* log);
gboolean purple_log_delete (PurpleLog* log);
char* purple_log_get_log_dir (PurpleLogType type, const char* name, PurpleAccount* account);
gint purple_log_compare (gconstpointer y, gconstpointer z);
gint purple_log_set_compare (gconstpointer y, gconstpointer z);
void purple_log_set_free (PurpleLogSet* set);
void purple_log_common_writer (PurpleLog* log, const char* ext);
GList* purple_log_common_lister (PurpleLogType type, const char* name, PurpleAccount* account, const char* ext, PurpleLogLogger* logger);
int purple_log_common_total_sizer (PurpleLogType type, const char* name, PurpleAccount* account, const char* ext);
int purple_log_common_sizer (PurpleLog* log);
gboolean purple_log_common_deleter (PurpleLog* log);
gboolean purple_log_common_is_deletable (PurpleLog* log);
PurpleLogLogger* purple_log_logger_new (const char* id, const char* name, int functions, ...);
void purple_log_logger_free (PurpleLogLogger* logger);
void purple_log_logger_add (PurpleLogLogger* logger);
void purple_log_logger_remove (PurpleLogLogger* logger);
void purple_log_logger_set (PurpleLogLogger* logger);
PurpleLogLogger* purple_log_logger_get (void);
GList* purple_log_logger_get_options (void);
void purple_log_init (void);
void* purple_log_get_handle (void);
void purple_log_uninit (void);
