const unsigned char* purple_network_ip_atoi (const char* ip);
void purple_network_set_public_ip (const char* ip);
const char* purple_network_get_public_ip (void);
const char* purple_network_get_local_system_ip (int fd);
const char* purple_network_get_my_ip (int fd);
void purple_network_listen_map_external (gboolean map_external);
PurpleNetworkListenData* purple_network_listen (unsigned short port, int socket_type, PurpleNetworkListenCallback cb, gpointer cb_data);
PurpleNetworkListenData* purple_network_listen_range (unsigned short start, unsigned short end, int socket_type, PurpleNetworkListenCallback cb, gpointer cb_data);
void purple_network_listen_cancel (PurpleNetworkListenData* listen_data);
unsigned short purple_network_get_port_from_fd (int fd);
gboolean purple_network_is_available (void);
void purple_network_force_online (void);
void* purple_network_get_handle (void);
void purple_network_set_stun_server (const gchar* stun_server);
const gchar* purple_network_get_stun_ip (void);
void purple_network_set_turn_server (const gchar* turn_server);
const gchar* purple_network_get_turn_ip (void);
void purple_network_remove_port_mapping (gint fd);
int purple_network_convert_idn_to_ascii (const gchar* in, gchar** out);
void purple_network_init (void);
void purple_network_uninit (void);
