void* purple_notify_searchresults (PurpleConnection* gc, const char* title, const char* primary, const char* secondary, PurpleNotifySearchResults* results, PurpleNotifyCloseCallback cb, gpointer user_data);
void purple_notify_searchresults_free (PurpleNotifySearchResults* results);
void purple_notify_searchresults_new_rows (PurpleConnection* gc, PurpleNotifySearchResults* results, void* data);
void purple_notify_searchresults_button_add (PurpleNotifySearchResults* results, PurpleNotifySearchButtonType type, PurpleNotifySearchResultsCallback cb);
void purple_notify_searchresults_button_add_labeled (PurpleNotifySearchResults* results, const char* label, PurpleNotifySearchResultsCallback cb);
PurpleNotifySearchResults* purple_notify_searchresults_new (void);
PurpleNotifySearchColumn* purple_notify_searchresults_column_new (const char* title);
void purple_notify_searchresults_column_add (PurpleNotifySearchResults* results, PurpleNotifySearchColumn* column);
void purple_notify_searchresults_row_add (PurpleNotifySearchResults* results, GList* row);
void* purple_notify_message (void* handle, PurpleNotifyMsgType type, const char* title, const char* primary, const char* secondary, PurpleNotifyCloseCallback cb, gpointer user_data);
void* purple_notify_email (void* handle, const char* subject, const char* from, const char* to, const char* url, PurpleNotifyCloseCallback cb, gpointer user_data);
void* purple_notify_emails (void* handle, size_t count, gboolean detailed, const char** subjects, const char** froms, const char** tos, const char** urls, PurpleNotifyCloseCallback cb, gpointer user_data);
void* purple_notify_formatted (void* handle, const char* title, const char* primary, const char* secondary, const char* text, PurpleNotifyCloseCallback cb, gpointer user_data);
void* purple_notify_userinfo (PurpleConnection* gc, const char* who, PurpleNotifyUserInfo* user_info, PurpleNotifyCloseCallback cb, gpointer user_data);
PurpleNotifyUserInfo* purple_notify_user_info_new (void);
void purple_notify_user_info_destroy (PurpleNotifyUserInfo* user_info);
GList* purple_notify_user_info_get_entries (PurpleNotifyUserInfo* user_info);
char* purple_notify_user_info_get_text_with_newline (PurpleNotifyUserInfo* user_info, const char* newline);
void purple_notify_user_info_add_pair (PurpleNotifyUserInfo* user_info, const char* label, const char* value);
void purple_notify_user_info_prepend_pair (PurpleNotifyUserInfo* user_info, const char* label, const char* value);
PurpleNotifyUserInfoEntry* purple_notify_user_info_entry_new (const char* label, const char* value);
void purple_notify_user_info_add_section_break (PurpleNotifyUserInfo* user_info);
void purple_notify_user_info_prepend_section_break (PurpleNotifyUserInfo* user_info);
void purple_notify_user_info_add_section_header (PurpleNotifyUserInfo* user_info, const char* label);
void purple_notify_user_info_prepend_section_header (PurpleNotifyUserInfo* user_info, const char* label);
void purple_notify_user_info_remove_last_item (PurpleNotifyUserInfo* user_info);
const gchar* purple_notify_user_info_entry_get_label (PurpleNotifyUserInfoEntry* user_info_entry);
void purple_notify_user_info_entry_set_label (PurpleNotifyUserInfoEntry* user_info_entry, const char* label);
const gchar* purple_notify_user_info_entry_get_value (PurpleNotifyUserInfoEntry* user_info_entry);
void purple_notify_user_info_entry_set_value (PurpleNotifyUserInfoEntry* user_info_entry, const char* value);
PurpleNotifyUserInfoEntryType purple_notify_user_info_entry_get_type (PurpleNotifyUserInfoEntry* user_info_entry);
void purple_notify_user_info_entry_set_type (PurpleNotifyUserInfoEntry* user_info_entry, PurpleNotifyUserInfoEntryType type);
void* purple_notify_uri (void* handle, const char* uri);
void purple_notify_close (PurpleNotifyType type, void* ui_handle);
void purple_notify_close_with_handle (void* handle);
void purple_notify_set_ui_ops (PurpleNotifyUiOps* ops);
PurpleNotifyUiOps* purple_notify_get_ui_ops (void);
void* purple_notify_get_handle (void);
void purple_notify_init (void);
void purple_notify_uninit (void);
