gboolean purple_privacy_permit_add (PurpleAccount* account, const char* name, gboolean local_only);
gboolean purple_privacy_permit_remove (PurpleAccount* account, const char* name, gboolean local_only);
gboolean purple_privacy_deny_add (PurpleAccount* account, const char* name, gboolean local_only);
gboolean purple_privacy_deny_remove (PurpleAccount* account, const char* name, gboolean local_only);
void purple_privacy_allow (PurpleAccount* account, const char* who, gboolean local, gboolean restore);
void purple_privacy_deny (PurpleAccount* account, const char* who, gboolean local, gboolean restore);
gboolean purple_privacy_check (PurpleAccount* account, const char* who);
void purple_privacy_set_ui_ops (PurplePrivacyUiOps* ops);
PurplePrivacyUiOps* purple_privacy_get_ui_ops (void);
void purple_privacy_init (void);
