PurpleProxyInfo* purple_proxy_info_new (void);
void purple_proxy_info_destroy (PurpleProxyInfo* info);
void purple_proxy_info_set_type (PurpleProxyInfo* info, PurpleProxyType type);
void purple_proxy_info_set_host (PurpleProxyInfo* info, const char* host);
void purple_proxy_info_set_port (PurpleProxyInfo* info, int port);
void purple_proxy_info_set_username (PurpleProxyInfo* info, const char* username);
void purple_proxy_info_set_password (PurpleProxyInfo* info, const char* password);
PurpleProxyType purple_proxy_info_get_type (const PurpleProxyInfo* info);
const char* purple_proxy_info_get_host (const PurpleProxyInfo* info);
int purple_proxy_info_get_port (const PurpleProxyInfo* info);
const char* purple_proxy_info_get_username (const PurpleProxyInfo* info);
const char* purple_proxy_info_get_password (const PurpleProxyInfo* info);
PurpleProxyInfo* purple_global_proxy_get_info (void);
void purple_global_proxy_set_info (PurpleProxyInfo* info);
void* purple_proxy_get_handle (void);
void purple_proxy_init (void);
void purple_proxy_uninit (void);
PurpleProxyInfo* purple_proxy_get_setup (PurpleAccount* account);
PurpleProxyConnectData* purple_proxy_connect (void* handle, PurpleAccount* account, const char* host, int port, PurpleProxyConnectFunction connect_cb, gpointer data);
PurpleProxyConnectData* purple_proxy_connect_udp (void* handle, PurpleAccount* account, const char* host, int port, PurpleProxyConnectFunction connect_cb, gpointer data);
PurpleProxyConnectData* purple_proxy_connect_socks5 (void* handle, PurpleProxyInfo* gpi, const char* host, int port, PurpleProxyConnectFunction connect_cb, gpointer data);
void purple_proxy_connect_cancel (PurpleProxyConnectData* connect_data);
void purple_proxy_connect_cancel_with_handle (void* handle);
