gboolean purple_ssl_is_supported (void);
const gchar* purple_ssl_strerror (PurpleSslErrorType error);
PurpleSslConnection* purple_ssl_connect (PurpleAccount* account, const char* host, int port, PurpleSslInputFunction func, PurpleSslErrorFunction error_func, void* data);
PurpleSslConnection* purple_ssl_connect_with_ssl_cn (PurpleAccount* account, const char* host, int port, PurpleSslInputFunction func, PurpleSslErrorFunction error_func, const char* ssl_host, void* data);
PurpleSslConnection* purple_ssl_connect_with_host_fd (PurpleAccount* account, int fd, PurpleSslInputFunction func, PurpleSslErrorFunction error_func, const char* host, void* data);
void purple_ssl_input_add (PurpleSslConnection* gsc, PurpleSslInputFunction func, void* data);
void purple_ssl_close (PurpleSslConnection* gsc);
size_t purple_ssl_read (PurpleSslConnection* gsc, void* buffer, size_t len);
size_t purple_ssl_write (PurpleSslConnection* gsc, const void* buffer, size_t len);
GList* purple_ssl_get_peer_certificates (PurpleSslConnection* gsc);
void purple_ssl_set_ops (PurpleSslOps* ops);
PurpleSslOps* purple_ssl_get_ops (void);
void purple_ssl_init (void);
void purple_ssl_uninit (void);
