PurpleValue* purple_value_new (PurpleType type, ...);
PurpleValue* purple_value_new_outgoing (PurpleType type, ...);
void purple_value_destroy (PurpleValue* value);
PurpleValue* purple_value_dup (const PurpleValue* value);
PurpleType purple_value_get_type (const PurpleValue* value);
unsigned int purple_value_get_subtype (const PurpleValue* value);
const char* purple_value_get_specific_type (const PurpleValue* value);
gboolean purple_value_is_outgoing (const PurpleValue* value);
void purple_value_set_char (PurpleValue* value, char data);
void purple_value_set_uchar (PurpleValue* value, unsigned char data);
void purple_value_set_boolean (PurpleValue* value, gboolean data);
void purple_value_set_short (PurpleValue* value, short data);
void purple_value_set_ushort (PurpleValue* value, unsigned short data);
void purple_value_set_int (PurpleValue* value, int data);
void purple_value_set_uint (PurpleValue* value, unsigned int data);
void purple_value_set_long (PurpleValue* value, long data);
void purple_value_set_ulong (PurpleValue* value, unsigned long data);
void purple_value_set_int64 (PurpleValue* value, gint64 data);
void purple_value_set_uint64 (PurpleValue* value, guint64 data);
void purple_value_set_string (PurpleValue* value, const char* data);
void purple_value_set_object (PurpleValue* value, void* data);
void purple_value_set_pointer (PurpleValue* value, void* data);
void purple_value_set_enum (PurpleValue* value, int data);
void purple_value_set_boxed (PurpleValue* value, void* data);
char purple_value_get_char (const PurpleValue* value);
unsigned char purple_value_get_uchar (const PurpleValue* value);
gboolean purple_value_get_boolean (const PurpleValue* value);
short purple_value_get_short (const PurpleValue* value);
unsigned short purple_value_get_ushort (const PurpleValue* value);
int purple_value_get_int (const PurpleValue* value);
unsigned int purple_value_get_uint (const PurpleValue* value);
long purple_value_get_long (const PurpleValue* value);
unsigned long purple_value_get_ulong (const PurpleValue* value);
gint64 purple_value_get_int64 (const PurpleValue* value);
guint64 purple_value_get_uint64 (const PurpleValue* value);
const char* purple_value_get_string (const PurpleValue* value);
void* purple_value_get_object (const PurpleValue* value);
void* purple_value_get_pointer (const PurpleValue* value);
int purple_value_get_enum (const PurpleValue* value);
void* purple_value_get_boxed (const PurpleValue* value);
