#define PASTE(a, b)     a##b
#define STRINGIZE(a)    #a

#if !defined (PTYPE) && !defined (ITYPE) && !defined (FTYPE)
# error Need to define at least one of PTYPE, ITYPE, FTYPE
#endif

#ifndef PTYPE
# define PTYPE(T, P)
#endif
#ifndef ITYPE
# define ITYPE(T, P)
#endif
#ifndef FTYPE
# define FTYPE(T, P)
#endif

PTYPE (Account,                         "Account")
PTYPE (AccountOption,                   "Account::Option")
PTYPE (AccountUiOps,                    "Account::UiOps")
PTYPE (AccountUserSplit,                "Account::UserSplit")
PTYPE (Buddy,                           "Buddy")
PTYPE (BuddyIcon,                       "Buddy::Icon")
PTYPE (BuddyIconSpec,                   "Buddy::IconSpec")
PTYPE (BuddyList,                       "BuddyList")
PTYPE (BlistNode,                       "BuddyList::Node")
PTYPE (BlistUiOps,                      "BuddyList::UiOps")
PTYPE (Certificate,                     "Certificate")
PTYPE (CertificatePool,                 "Certificate::Pool")
PTYPE (CertificateScheme,               "Certificate::Scheme")
PTYPE (CertificateVerificationRequest,  "Certificate::VerificationRequest")
PTYPE (CertificateVerifier,             "Certificate::Verifier")
PTYPE (Chat,                            "Chat")
PTYPE (Cipher,                          "Cipher")
PTYPE (CipherContext,                   "Cipher::Context")
PTYPE (CipherOps,                       "Cipher::Ops")
PTYPE (Connection,                      "Connection")
PTYPE (ConnectionErrorInfo,             "Connection::ErrorInfo")
PTYPE (ConnectionUiOps,                 "Connection::UiOps")
PTYPE (Contact,                         "Contact")
PTYPE (ConvChatBuddy,                   "Conversation::Chat::Buddy")
PTYPE (ConvChat,                        "Conversation::Chat")
PTYPE (Conversation,                    "Conversation")
PTYPE (ConversationUiOps,               "Conversation::UiOps")
PTYPE (ConvIm,                          "Conversation::Im")
PTYPE (ConvMessage,                     "Conversation::Message")
PTYPE (Core,                            "Core")
PTYPE (CoreUiOps,                       "Core::UiOps")
PTYPE (DebugUiOps,                      "Debug::UiOps")
PTYPE (DnsQueryData,                    "DnsQuery::Data")
PTYPE (DnsQueryUiOps,                   "DnsQuery::UiOps")
PTYPE (EventLoopUiOps,                  "EventLoop::UiOps")
PTYPE (Group,                           "Group")
PTYPE (IdleUiOps,                       "Idle::UiOps")
PTYPE (Log,                             "Log")
PTYPE (LogLogger,                       "Log::Logger")
PTYPE (LogReadFlags,                    "Log::ReadFlags")
PTYPE (LogSet,                          "Log::Set")
PTYPE (MenuAction,                      "Menu::Action")
PTYPE (MimeDocument,                    "Mime::Document")
PTYPE (MimePart,                        "Mime::Part")
PTYPE (NetworkListenData,               "Network::ListenData")
PTYPE (NotifySearchColumn,              "Notify::SearchColumn")
PTYPE (NotifySearchResults,             "Notify::SearchResults")
PTYPE (NotifyUiOps,                     "Notify::UiOps")
PTYPE (NotifyUserInfoEntry,             "Notify::UserInfo::Entry")
PTYPE (NotifyUserInfo,                  "Notify::UserInfo")
PTYPE (Plugin,                          "Plugin")
PTYPE (Pounce,                          "Pounce")
PTYPE (Presence,                        "Presence")
PTYPE (PresenceContext,                 "Presence::Context")
PTYPE (PrivacyUiOps,                    "Privacy::UiOps")
PTYPE (ProxyConnectData,                "Proxy::ConnectData")
PTYPE (ProxyInfo,                       "Proxy::Info")
PTYPE (RequestFieldGroup,               "Request::FieldGroup")
PTYPE (RequestField,                    "Request::Field")
PTYPE (RequestFields,                   "Request::Fields")
PTYPE (RequestUiOps,                    "Request::UiOps")
PTYPE (Roomlist,                        "Roomlist")
PTYPE (RoomlistField,                   "Roomlist::Field")
PTYPE (RoomlistRoom,                    "Roomlist::Room")
PTYPE (RoomlistUiOps,                   "Roomlist::UiOps")
PTYPE (SavedStatus,                     "SavedStatus")
PTYPE (SavedStatusSub,                  "SavedStatus::Sub")
PTYPE (Smiley,                          "Smiley")
PTYPE (SoundTheme,                      "Sound::Theme")
PTYPE (SoundUiOps,                      "Sound::UiOps")
PTYPE (SrvQueryData,                    "SrvQueryData")
PTYPE (SslConnection,                   "Ssl::Connection")
PTYPE (SslOps,                          "SslOps")
PTYPE (Status,                          "Status")
PTYPE (StatusAttr,                      "Status::Attr")
PTYPE (StatusType,                      "Status::Type")
PTYPE (StoredImage,                     "StoredImage")
PTYPE (Stringref,                       "Stringref")
PTYPE (StunNatDiscovery,                "StunNatDiscovery")
PTYPE (TxtResponse,                     "TxtResponse")
PTYPE (UtilFetchUrlData,                "UtilFetchUrlData")
PTYPE (Value,                           "Value")
PTYPE (Whiteboard,                      "Whiteboard")
PTYPE (WhiteboardPrplOps,               "Whiteboard::PrplOps")
PTYPE (WhiteboardUiOps,                 "Whiteboard::UiOps")
PTYPE (Xfer,                            "Xfer")
PTYPE (XferUiOps,                       "Xfer::UiOps")

ITYPE (BlistNodeFlags,                  "BlistNodeFlags")
ITYPE (BlistNodeType,                   "BlistNodeType")
ITYPE (CertificateVerificationStatus,   "CertificateVerificationStatus")
ITYPE (CipherBatchMode,                 "CipherBatchMode")
ITYPE (CmdFlag,                         "CmdFlag")
//ITYPE (CmdId,                           "CmdId")
ITYPE (CmdPriority,                     "CmdPriority")
ITYPE (CmdStatus,                       "CmdStatus")
ITYPE (ConnectionError,                 "ConnectionError")
ITYPE (ConnectionFlags,                 "ConnectionFlags")
ITYPE (ConnectionState,                 "ConnectionState")
ITYPE (ConvChatBuddyFlags,              "ConvChatBuddyFlags")
ITYPE (ConversationType,                "ConversationType")
ITYPE (ConvUpdateType,                  "ConvUpdateType")
ITYPE (DebugLevel,                      "DebugLevel")
ITYPE (InputCondition,                  "InputCondition")
ITYPE (LogType,                         "LogType")
ITYPE (MessageFlags,                    "MessageFlags")
ITYPE (NotifyMsgType,                   "NotifyMsgType")
ITYPE (NotifySearchButtonType,          "NotifySearchButtonType")
ITYPE (NotifyType,                      "NotifyType")
ITYPE (NotifyUserInfoEntryType,         "NotifyUserInfoEntryType")
ITYPE (PounceEvent,                     "PounceEvent")
ITYPE (PounceOption,                    "PounceOption")
ITYPE (PrefType,                        "PrefType")
ITYPE (PresenceContext,                 "PresenceContext")
ITYPE (ProxyType,                       "ProxyType")
ITYPE (RequestFieldType,                "RequestFieldType")
ITYPE (RequestType,                     "RequestType")
ITYPE (RoomlistFieldType,               "RoomlistFieldType")
ITYPE (RoomlistRoomType,                "RoomlistRoomType")
ITYPE (SoundEventID,                    "SoundEventID")
ITYPE (SslErrorType,                    "SslErrorType")
ITYPE (StatusPrimitive,                 "StatusPrimitive")
ITYPE (Type,                            "Type")
ITYPE (TypingState,                     "TypingState")
ITYPE (XferStatusType,                  "XferStatusType")
ITYPE (XferType,                        "XferType")

FTYPE (AccountRegistrationCb,           "AccountRegistrationCb")
FTYPE (AccountRequestAuthorizationCb,   "AccountRequestAuthorizationCb")
//FTYPE (AccountUnregistrationCb,         "AccountUnregistrationCb")
//FTYPE (Callback,                        "Callback")
FTYPE (CertificateVerifiedCallback,     "CertificateVerifiedCallback")
FTYPE (CmdFunc,                         "CmdFunc")
FTYPE (ConversationFunction,            "ConversationFunction")
FTYPE (DnsQueryConnectFunction,         "DnsQueryConnectFunction")
FTYPE (FilterAccountFunc,               "FilterAccountFunc")
FTYPE (InfoFieldFormatCallback,         "InfoFieldFormatCallback")
FTYPE (InputFunction,                   "InputFunction")
FTYPE (NetworkListenCallback,           "NetworkListenCallback")
//FTYPE (NotifyCloseCallback,             "NotifyCloseCallback")
FTYPE (NotifySearchResultsCallback,     "NotifySearchResultsCallback")
FTYPE (PounceCb,                        "PounceCb")
FTYPE (PounceFunction,                  "PounceFunction")
FTYPE (PrefCallback,                    "PrefCallback")
FTYPE (ProxyConnectFunction,            "ProxyConnectFunction")
FTYPE (SrvCallback,                     "SrvCallback")
FTYPE (SslErrorFunction,                "SslErrorFunction")
FTYPE (SslInputFunction,                "SslInputFunction")
FTYPE (TxtCallback,                     "TxtCallback")
FTYPE (UtilFetchUrlCallback,            "UtilFetchUrlCallback")
FTYPE (XferAckFunction,                 "XferAckFunction")
FTYPE (XferFunction,                    "XferFunction")
FTYPE (XferReadFunction,                "XferReadFunction")
FTYPE (XferWriteFunction,               "XferWriteFunction")

#undef PTYPE
#undef ITYPE
#undef FTYPE
